# Generated by Django 5.2.5 on 2025-09-02 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Array', 'Array'), ('String', 'String'), ('LinkedList', 'LinkedList'), ('Tree', 'Tree'), ('Graph', 'Graph'), ('DP', 'DP'), ('Backtracking', 'Backtracking'), ('Other', 'Other')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('status', models.CharField(choices=[('Solved', 'Solved'), ('Attempted', 'Attempted'), ('Unsolved', 'Unsolved')], default='Unsolved', max_length=10)),
                ('date_solved', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
